name: Build and Push Docker Image on Release or Dispatch

on:
  release:
    types: [created]
  repository_dispatch:
    types: [trigger-build]

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Determine Tag
      id: vars
      run: |
        if [[ ${{ github.event_name }} == 'release' ]]; then
          echo "::set-output name=tag::${GITHUB_REF#refs/tags/}"
        elif [[ ${{ github.event_name }} == 'repository_dispatch' ]]; then
          echo "::set-output name=tag::${{ github.event.client_payload.tag }}"
        fi

    - name: Build and Push Docker Image
      run: |
        docker build -t hamzadevops/angular-semantic-release:${{ steps.vars.outputs.tag }} .
        docker push hamzadevops/angular-semantic-release:${{ steps.vars.outputs.tag }}
