name: CI/CD Pipeline for Angular Application

on:
  push:
    branches:
      - main
  workflow_dispatch:  # Allows manual trigger from GitHub UI
    inputs:
      branch:
        description: 'Branch to deploy'
        required: true
        default: 'main'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0 # Ensures all tags and history are fetched

      - name: Get tag
        id: tag
        uses: WyriHaximus/github-action-get-previous-tag@8a0e045f02c0a3a04e1452df58b90fc7e555e950

      - name: Set correct environment
        run: |
          TAG=${{ steps.tag.outputs.tag }}
          echo "TAG=$TAG" >> "$GITHUB_ENV"

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Retrieve metadata
        id: metadata
        uses: docker/metadata-action@e5622373a38e60fb6d795a4421e56882f2d7a681
        with:
          images: hamzadevops/angular-semantic-release
          tags: |
            type=semver,pattern={{major}}.{{minor}}.{{patch}},value=${{ env.TAG }}
            type=semver,pattern={{major}}.{{minor}},value=${{ env.TAG }}
            type=semver,pattern={{major}},value=${{ env.TAG }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ${{ steps.metadata.outputs.tags }}

      - name: Set up Kubeconfig
        run: |
          mkdir -p $HOME/.kube
          echo "${{ secrets.KUBECONFIG }}" > $HOME/.kube/config

      - name: Set up Kubectl
        uses: azure/setup-kubectl@v1
        with:
          kubeconfig: $HOME/.kube/config

      - name: Deploy to Kubernetes
        run: |
          kubectl set image deployment/angular-app-deployment my-container=hamzadevops/angular-semantic-release:${{ env.TAG }} --record
