name: CI/CD Pipeline for Angular Application

on:
  push:
    branches:
      - main
  workflow_dispatch:  # Allows manual trigger from GitHub UI
    inputs:
      branch:
        description: 'Branch to deploy'
        required: true
        default: 'main'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0 # Ensures all tags and history are fetched
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
              hamzadevops/angular-semantic-release
          tags: |
              type=ref,event=branch
              type=ref,event=pr
              type=semver,pattern={{version}}
              type=semver,pattern={{major}}.{{minor}}

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build and tag Docker image
        run: |
          echo "Building Docker image with tag ${{ steps.meta.outputs.tags }}"
          docker build -t hamzadevops/angular-semantic-release:${{ steps.meta.outputs.tags }} .

      - name: Push Docker image to Docker Hub
        run: |
            echo "Pushing image to Docker Hub"
            docker push hamzadevops/angular-semantic-release:${{ steps.meta.outputs.tags }}
          
      - name: Set up Kubeconfig
        run: |
          mkdir -p $HOME/.kube
          echo "${{ secrets.KUBECONFIG }}" > $HOME/.kube/config

      - name: Set up Kubectl
        uses: azure/setup-kubectl@v1

      - name: Deploy to Kubernetes
        run: |
          sed -i 's/${IMAGE_TAG}/${{ steps.meta.outputs.tags }}/g' deployment.yml
          kubectl apply -f deployment.yml
