name: CI/CD Pipeline for Angular Application

on:
  push:
    branches:
      - main
  workflow_dispatch:  # Allows manual trigger from GitHub UI
    inputs:
      branch:
        description: 'Branch to deploy'
        required: true
        default: 'main'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0 # Ensures all tags and history are fetched

      - name: Retrieve metadata
        id: metadata
        uses: docker/metadata-action@e5622373a38e60fb6d795a4421e56882f2d7a681
        with:
          images: hamzadevops/angular-semantic-release
          tags: |
            type=semver,pattern={{major}}.{{minor}}.{{patch}},value=${{ env.TAG }}

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build and tag Docker image
        run: |
          echo "Building Docker image with tag ${{ env.TAG }}"
          docker build -t hamzadevops/angular-semantic-release:${{ env.TAG }} .

      - name: Push Docker image to Docker Hub
        run: |
            echo "Pushing image to Docker Hub"
            docker push hamzadevops/angular-semantic-release:${{ env.TAG }}
          
      - name: Set up Kubeconfig
        run: |
          mkdir -p $HOME/.kube
          echo "${{ secrets.KUBECONFIG }}" > $HOME/.kube/config

      - name: Set up Kubectl
        uses: azure/setup-kubectl@v1

      - name: Deploy to Kubernetes
        run: |
          sed -i 's/${IMAGE_TAG}/${{ env.TAG }}/g' deployment.yml
          kubectl apply -f deployment.yml
