name: CI/CD Pipeline for Angular Application

on:
  push:
    branches:
      - main
  workflow_dispatch:  # Allows manual trigger from GitHub UI
    inputs:
      branch:
        description: 'Branch to deploy'
        required: true
        default: 'main'
      tag:
        description: 'Docker image tag'
        required: false

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.inputs.branch || 'main' }}  # Default to main if no branch input

      - name: Build Docker Image
        run: |
          docker build -t hamzadevops/angular-semantic-release:${{ github.event.inputs.tag || github.sha }} .
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
          docker push hamzadevops/angular-semantic-release:${{ github.event.inputs.tag || github.sha }}

      - name: Set up Kubeconfig
        run: |
          mkdir -p $HOME/.kube  # Ensure the .kube directory exists
          echo "${{ secrets.KUBECONFIG }}" > $HOME/.kube/config

      - name: Set up Kubectl
        uses: azure/setup-kubectl@v1
        with:
          kubeconfig: $HOME/.kube/config

      - name: Deploy to Kubernetes
        run: |
          kubectl apply -f deployment.yml hamzadevops/angular-semantic-release:${{ github.event.inputs.tag || latest }}

      - name: Configure Ingress
        run: |
          kubectl patch ingress nginx-ingress-controller -p "{\"spec\":{\"rules\":[{\"host\":\"143.42.222.111\",\"http\":{\"paths\":[{\"path\":\"/\",\"backend\":{\"serviceName\":\"angular-app-service\",\"servicePort\":80}}]}}]}}"
