name: CI/CD Pipeline for Angular Application

on:
  push:
    branches:
      - 'feature/*'
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch to deploy'
        required: true
        default: 'main'
      tag:
        description: 'Docker image tag to deploy'
        required: false

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      issues: write
      pull-requests: write

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0 # Ensures all tags and history are fetched

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20.9.0'

      - name: Install Dependencies
        run: npm ci

      - name: Build Project
        run: npm run build

      - name: Run CI Tests
        run: npm test

      - name: Determine if Semantic Release is Needed
        if: contains(github.ref, 'features')
        run: npx semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Get previous tag
        id: prev_tag
        uses: WyriHaximus/github-action-get-previous-tag@8a0e045f02c0a3a04e1452df58b90fc7e555e950

      - name: Set environment variables for TAG
        run: echo "TAG=${{ steps.prev_tag.outputs.tag }}" >> $GITHUB_ENV

      - name: Retrieve Docker metadata
        id: metadata
        uses: docker/metadata-action@e5622373a38e60fb6d795a4421e56882f2d7a681
        with:
          images: hamzadevops/angular-semantic-release
          tags: |
            type=semver,pattern={{major}}.{{minor}}.{{patch}},value=${{ env.TAG }}

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and tag Docker image
        run: |
          echo "Building Docker image with tag ${{ env.TAG }}"
          docker build -t hamzadevops/angular-semantic-release:${{ env.TAG }} .

      - name: Push Docker image to Docker Hub
        run: |
          echo "Pushing image to Docker Hub"
          docker push hamzadevops/angular-semantic-release:${{ env.TAG }}

  deploy:
    needs: build-and-release
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'workflow_dispatch' }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Kubeconfig
        run: |
          mkdir -p $HOME/.kube
          echo "${{ secrets.KUBECONFIG }}" > $HOME/.kube/config

      - name: Set up Kubectl
        uses: azure/setup-kubectl@v1

      - name: Deploy to Kubernetes
        run: |
          sed -i 's/\${IMAGE_TAG}/${{ github.event.inputs.tag }}/g' deployment.yml
          kubectl apply -f deployment.yml
